nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["*"]
    allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600 # définir la durée de vie du cache des résultats
  paths:
    "^/api/": null
