vich_uploader:
  db_driver: orm

  mappings:
    articleiIlustration:
      uri_prefix: "%app.path.article_illustrations%"
      upload_destination: "%kernel.project_dir%/public/%app.path.article_illustrations%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
