vich_uploader:
  db_driver: orm

  mappings:
    articleIllustration:
      uri_prefix: "%app.path.article_illustrations%" # chemin d'accès de la ressource depuis l'application web
      upload_destination: "%kernel.project_dir%/public/%app.path.article_illustrations%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
