vich_uploader:
  db_driver: orm

  mappings:
    articleIllustration:
      uri_prefix: "%app.path.article_illustrations%" # chemin d'accès de la ressource depuis l'application web
      upload_destination: "%kernel.project_dir%/public/%app.path.article_illustrations%" # dossier de destination des images d'illustrations principales
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # stratégie de nommage des fichiers
    cv:
      uri_prefix: "%app.path.cv%" # chemin d'accès de la ressource depuis l'application web
      upload_destination: "%kernel.project_dir%/public/%app.path.cv%" # dossier de destination des CV soumis
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
