# version: '3.8'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    env_file: 
      - .env
      - .env.local #
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:30000/healthz" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - "30000:80"

volumes:
  mercure_data:
  mercure_config:
