# version: '3.8'

services:
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      # SERVER_NAME: ':80'
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
    # Comment the following line to disable the development mode
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev --adapter caddyfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthz" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
      - ./config/docker/Caddyfile.dev:/etc/caddy/Caddyfile.dev:ro
    ports:
      - "80:80"
      - "443:443"

volumes:
  mercure_data:
  mercure_config:
