controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
  defaults:
    schemes: ["HTTPS"] # Limitation du protocole de communication utilisé dans l'app uniquement en HTTPS de façon sécurisé
